services:
  - type: web
    name: monopoly-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
