import type { CardDefinition } from '../types/index';

export const CHANCE_CARDS: CardDefinition[] = [
  {
    id: 'CHANCE_01',
    name: 'Tiến tới ô BẮT ĐẦU (GO)',
    deck: 'CHANCE',
    action: 'MOVE_TO',
    params: { target: 0, passGoSalary: true },
    description: 'Di chuyển thẳng về ô BẮT ĐẦU và nhận ngay $200 tiền lương.',
  },
  {
    id: 'CHANCE_02',
    name: 'Chuyến đi Hà Nội Downtown',
    deck: 'CHANCE',
    action: 'MOVE_TO',
    params: { target: 39, passGoSalary: true },
    description:
      'Di chuyển đến Hà Nội Downtown. Nếu đường đi ngang qua ô BẮT ĐẦU, bạn nhận thêm $200. Nếu ô đang có chủ, bạn phải trả tiền thuê cho họ.',
  },
  {
    id: 'CHANCE_03',
    name: 'Ghé thăm Đà Nẵng Downtown',
    deck: 'CHANCE',
    action: 'MOVE_TO',
    params: { target: 37, passGoSalary: true },
    description:
      'Di chuyển đến Đà Nẵng Downtown. Nếu đường đi ngang qua ô BẮT ĐẦU, bạn nhận thêm $200. Nếu ô đang có chủ, bạn phải trả tiền thuê cho họ.',
  },
  {
    id: 'CHANCE_04',
    name: 'Di chuyển tới Ga Hà Nội',
    deck: 'CHANCE',
    action: 'MOVE_TO',
    params: { target: 5, passGoSalary: true },
    description:
      'Di chuyển đến Ga Hà Nội. Nếu đường đi ngang qua ô BẮT ĐẦU, bạn nhận thêm $200. Nếu nhà ga đang có chủ, bạn phải trả tiền thuê cho họ.',
  },
  {
    id: 'CHANCE_05',
    name: 'Di chuyển tới Bãi Nghỉ (Free Parking)',
    deck: 'CHANCE',
    action: 'MOVE_TO',
    params: { target: 20, passGoSalary: true },
    description:
      'Di chuyển đến Bãi Nghỉ (Free Parking). Nếu đường đi ngang qua ô BẮT ĐẦU, bạn nhận thêm $200.',
  },
  {
    id: 'CHANCE_06',
    name: 'Tiến 3 ô',
    deck: 'CHANCE',
    action: 'MOVE_RELATIVE',
    params: { steps: 3, passGoSalary: true },
    description: 'Tiến thêm 3 ô về phía trước. Nếu đường đi ngang qua ô BẮT ĐẦU, bạn nhận thêm $200.',
  },
  {
    id: 'CHANCE_07',
    name: 'Lùi 3 ô',
    deck: 'CHANCE',
    action: 'MOVE_RELATIVE',
    params: { steps: -3, passGoSalary: false },
    description: 'Lùi lại 3 ô so với vị trí hiện tại.',
  },
  {
    id: 'CHANCE_08',
    name: 'Nhận thưởng đầu tư bất động sản',
    deck: 'CHANCE',
    action: 'RECEIVE_BANK',
    params: { amount: 150 },
    description: 'Ngân hàng thưởng cho bạn $150 nhờ khoản đầu tư bất động sản sinh lời.',
  },
  {
    id: 'CHANCE_09',
    name: 'Thắng cổ phiếu thị trường',
    deck: 'CHANCE',
    action: 'RECEIVE_BANK',
    params: { amount: 100 },
    description: 'Bạn thắng lớn nhờ cổ phiếu thị trường tăng giá, nhận ngay $100.',
  },
  {
    id: 'CHANCE_10',
    name: 'Nộp thuế thu nhập cá nhân',
    deck: 'CHANCE',
    action: 'PAY_BANK',
    params: { amount: 50 },
    description: 'Bạn phải nộp $50 thuế thu nhập cá nhân cho ngân hàng.',
  },
  {
    id: 'CHANCE_11',
    name: 'Phạt vi phạm giao thông',
    deck: 'CHANCE',
    action: 'PAY_BANK',
    params: { amount: 100 },
    description: 'Bạn bị phạt $100 vì vi phạm giao thông, nộp ngay cho ngân hàng.',
  },
  {
    id: 'CHANCE_12',
    name: 'Tiệc mừng sinh nhật',
    deck: 'CHANCE',
    action: 'RECEIVE_ALL_PLAYERS',
    params: { amount: 20 },
    description: 'Hôm nay là sinh nhật bạn! Mỗi người chơi khác phải trả cho bạn $20.',
  },
  {
    id: 'CHANCE_13',
    name: 'Đi thẳng vào Trại Giam',
    deck: 'CHANCE',
    action: 'GO_TO_JAIL',
    params: { target: 10, passGoSalary: false },
    description: 'Bạn bị bắt và đưa thẳng vào Trại Giam. Không đi qua ô BẮT ĐẦU, không nhận lương $200.',
  },
  {
    id: 'CHANCE_14',
    name: 'Thẻ Ra Tù Miễn Phí',
    deck: 'CHANCE',
    action: 'GET_OUT_OF_JAIL_CARD',
    params: { keepable: true },
    description: 'Bạn nhận được Thẻ Ra Tù Miễn Phí — giữ lại để dùng bất cứ lúc nào bạn bị vào tù.',
  },
  {
    id: 'CHANCE_15',
    name: 'Sửa chữa nhà cửa toàn diện',
    deck: 'CHANCE',
    action: 'REPAIR_BUILDINGS',
    params: { perHouse: 25, perHotel: 100 },
    description:
      'Bạn phải trả chi phí sửa chữa: $25 cho mỗi nhà và $100 cho mỗi khách sạn bạn đang sở hữu.',
  },
  {
    id: 'CHANCE_16',
    name: 'Tái thiết đô thị',
    deck: 'CHANCE',
    action: 'REPAIR_BUILDINGS',
    params: { perHouse: 40, perHotel: 115 },
    description:
      'Thành phố yêu cầu tái thiết đô thị: bạn phải trả $40 cho mỗi nhà và $115 cho mỗi khách sạn bạn đang sở hữu.',
  },
];

export const COMMUNITY_CARDS: CardDefinition[] = [
  {
    id: 'COMMUNITY_01',
    name: 'Nhận cổ tức từ ngân hàng',
    deck: 'COMMUNITY',
    action: 'RECEIVE_BANK',
    params: { amount: 200 },
    description: 'Ngân hàng chia cổ tức cho bạn $200.',
  },
  {
    id: 'COMMUNITY_02',
    name: 'Nhận hoàn thuế thu nhập',
    deck: 'COMMUNITY',
    action: 'RECEIVE_BANK',
    params: { amount: 100 },
    description: 'Bạn được hoàn thuế thu nhập $100.',
  },
  {
    id: 'COMMUNITY_03',
    name: 'Bán cổ phiếu quỹ cộng đồng',
    deck: 'COMMUNITY',
    action: 'RECEIVE_BANK',
    params: { amount: 50 },
    description: 'Bạn bán cổ phiếu quỹ cộng đồng, thu về $50.',
  },
  {
    id: 'COMMUNITY_04',
    name: 'Nhận tiền trúng thưởng xổ số',
    deck: 'COMMUNITY',
    action: 'RECEIVE_BANK',
    params: { amount: 75 },
    description: 'Bạn trúng thưởng xổ số $75.',
  },
  {
    id: 'COMMUNITY_05',
    name: 'Nhận thưởng sinh nhật',
    deck: 'COMMUNITY',
    action: 'RECEIVE_ALL_PLAYERS',
    params: { amount: 10 },
    description: 'Hôm nay là sinh nhật bạn! Mỗi người chơi khác phải trả cho bạn $10.',
  },
  {
    id: 'COMMUNITY_06',
    name: 'Nhận hỗ trợ bảo hiểm y tế',
    deck: 'COMMUNITY',
    action: 'RECEIVE_BANK',
    params: { amount: 100 },
    description: 'Bạn nhận hỗ trợ bảo hiểm y tế $100.',
  },
  {
    id: 'COMMUNITY_07',
    name: 'Nhận thưởng quỹ từ thiện',
    deck: 'COMMUNITY',
    action: 'RECEIVE_BANK',
    params: { amount: 25 },
    description: 'Quỹ từ thiện cộng đồng trao thưởng cho bạn $25.',
  },
  {
    id: 'COMMUNITY_08',
    name: 'Thanh toán viện phí',
    deck: 'COMMUNITY',
    action: 'PAY_BANK',
    params: { amount: 100 },
    description: 'Bạn phải thanh toán viện phí $100 cho ngân hàng.',
  },
  {
    id: 'COMMUNITY_09',
    name: 'Nộp học phí đại học',
    deck: 'COMMUNITY',
    action: 'PAY_BANK',
    params: { amount: 50 },
    description: 'Bạn phải nộp học phí đại học $50.',
  },
  {
    id: 'COMMUNITY_10',
    name: 'Nộp phí tư vấn pháp lý',
    deck: 'COMMUNITY',
    action: 'PAY_BANK',
    params: { amount: 150 },
    description: 'Bạn phải trả phí tư vấn pháp lý $150.',
  },
  {
    id: 'COMMUNITY_11',
    name: 'Đóng góp từ thiện',
    deck: 'COMMUNITY',
    action: 'PAY_ALL_PLAYERS',
    params: { amount: 20 },
    description: 'Bạn phải đóng góp từ thiện: trả cho mỗi người chơi khác $20.',
  },
  {
    id: 'COMMUNITY_12',
    name: 'Trở về ô BẮT ĐẦU (GO)',
    deck: 'COMMUNITY',
    action: 'MOVE_TO',
    params: { target: 0, passGoSalary: true },
    description: 'Di chuyển thẳng về ô BẮT ĐẦU và nhận ngay $200 tiền lương.',
  },
  {
    id: 'COMMUNITY_13',
    name: 'Đi thẳng vào Trại Giam',
    deck: 'COMMUNITY',
    action: 'GO_TO_JAIL',
    params: { target: 10, passGoSalary: false },
    description: 'Bạn bị bắt và đưa thẳng vào Trại Giam. Không đi qua ô BẮT ĐẦU, không nhận lương $200.',
  },
  {
    id: 'COMMUNITY_14',
    name: 'Thẻ Ra Tù Miễn Phí',
    deck: 'COMMUNITY',
    action: 'GET_OUT_OF_JAIL_CARD',
    params: { keepable: true },
    description: 'Bạn nhận được Thẻ Ra Tù Miễn Phí — giữ lại để dùng bất cứ lúc nào bạn bị vào tù.',
  },
  {
    id: 'COMMUNITY_15',
    name: 'Sửa chữa nâng cấp khu phố',
    deck: 'COMMUNITY',
    action: 'REPAIR_BUILDINGS',
    params: { perHouse: 40, perHotel: 115 },
    description:
      'Khu phố cần nâng cấp sửa chữa: bạn phải trả $40 cho mỗi nhà và $115 cho mỗi khách sạn bạn đang sở hữu.',
  },
  {
    id: 'COMMUNITY_16',
    name: 'Kiểm tra sức khỏe định kỳ',
    deck: 'COMMUNITY',
    action: 'PAY_BANK',
    params: { amount: 25 },
    description: 'Bạn phải trả $25 phí kiểm tra sức khỏe định kỳ.',
  },
];
